configs: "../common/sbm_configs/shared_memory.yaml"
include_variables:
  - "../common/sbm_configs/shared_memory_vars.yaml"

variables:
  benchmark:
    - "syncbench"
    - "schedbench"
    - "taskbench"
    - "arraybench_1"
    - "arraybench_243"
    - "arraybench_2187"
    # - "arraybench_19683"
    - "arraybench_59049"


jobs:
  - config: "{compiler}__{compiler_opt[compiler]}__{compiler_extra_flags_name[compiler]}____{ncpus}"
    config_jobs:
      - tag: "{compiler}_{isa}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{benchmark}_C{ncpus}"
        category: "{benchmark}"
        preprocess: "{energy_measure_start}"
        command: "./bin/{compiler}_{isa}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}/{benchmark}"
        postprocess: '{energy_measure_stop}'
