sequential: true

configs: "../common/sbm_configs/shared_memory.yaml"
include_variables:
  - "../common/sbm_configs/shared_memory_vars.yaml"
  - "vars.yaml"


preprocess: |
  mkdir -p bin
  cd NPB-OMP
  rm config/make.def
  cat > config/make.def<< EOF
  # ===========================================================================
  # NAS Parallel Benchmarks 3.4
  # OpenMP Versions
  # Site- and platform-specific definitions
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # C Compiler Settings (used for IS and DC benchmarks)
  # ---------------------------------------------------------------------------

  # C compiler
  CC = {compiler_cxx[compiler]}
  CLINK = {compiler_cxx[compiler]}

  # Compiler and linker flags
  CFLAGS = {compiler_opt[compiler]} {compiler_common[compiler]} {compiler_march} {compiler_extra_flags[compiler_extra_flags_name]}
  CLINKFLAGS = {compiler_opt[compiler]} {compiler_common[compiler]} {compiler_march} {compiler_extra_flags[compiler_extra_flags_name]}

  # Include and library paths
  C_INC  =
  C_LIB  = -lm

  # ---------------------------------------------------------------------------
  # Utilities C compiler (for scripts and small helpers)
  # ---------------------------------------------------------------------------

  UCC = gcc

  # ---------------------------------------------------------------------------
  # Executable output directory
  # ---------------------------------------------------------------------------

  # Relative to <benchmark> directories
  BINDIR = ../bin

  # ---------------------------------------------------------------------------
  # Random number generator (used by benchmarks)
  # ---------------------------------------------------------------------------

  RAND = randdp

  # ---------------------------------------------------------------------------
  # Timing module
  # ---------------------------------------------------------------------------

  WTIME = wtime.cpp

  # ---------------------------------------------------------------------------
  # Optional machine definitions
  # ---------------------------------------------------------------------------
  # MACHINE = -DX86  # Uncomment if a specific machine macro is needed
  EOF

  make clean
  mkdir -p bin
  NPB_BENCH={benchmark}
  BIN_NAME="{benchmark}_{class[benchmark]}_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}.x"
  
  
command: 'make {benchmark} CLASS={class[benchmark]}'
postprocess: 'mv "bin/${NPB_BENCH,,}.{class[benchmark]}" "../bin/$BIN_NAME" && {compiler_disass[compiler]} "../bin/$BIN_NAME" > "$SBATCHMAN_JOB_DIR/$BIN_NAME".asm'
check: '[[ -f "../bin/$BIN_NAME" ]]'


jobs:
  - config: "{compiler}__{compiler_opt[compiler]}__{compiler_extra_flags_name[compiler]}____1"
    config_jobs:
      - tag: "compile_NPB-OMP_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{benchmark}_{class[benchmark]}"
