configs: "../common/sbm_configs/shared_memory.yaml"
include_variables:
  - "../common/sbm_configs/shared_memory_vars.yaml"
  - "vars.yaml"


jobs:
  - config: "{compiler}__{compiler_opt[compiler]}__{compiler_extra_flags_name[compiler]}____{ncpus}"
    config_jobs:
      - tag: "NPB-OMP_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{benchmark}_{class[benchmark]}"
        preprocess: "{energy_measure_start}"
        command: "bin/{benchmark}_{class[benchmark]}_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}.x"
        postprocess: "{energy_measure_stop}"
