sequential: true

configs: "../common/sbm_configs/shared_memory.yaml"
include_variables:
  - "../common/sbm_configs/shared_memory_vars.yaml"
  - "vars.yaml"


variables:
  # TODO delete
  compiler_opt:
    map:
      default: ['-O3']
  compiler_extra_flags_name:
    map:
      default: ['autovec']

jobs:
  - config: "{compiler}__{compiler_opt[compiler]}__{compiler_extra_flags_name[compiler]}____1"
    config_jobs:

      # Mutex
      - tag: "compile_MergedCSR-BFS_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{implementation}_{chunksize}_{ncpus}"
        variables:
          implementation: ['mutex']
        preprocess: |
          mkdir -p bin
          cd MergedCSR_{implementation}/pthreads
          make clean
          BIN_NAME="bfs_{implementation}_chunksize{chunksize}_{ncpus}cpus_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}"
        command: "CHUNK_SIZE={chunksize} MAX_THREADS={ncpus} make bin/bfs"
        postprocess: 'mv bin/bfs "../../bin/$BIN_NAME" && {compiler_disass[compiler]} "../../bin/$BIN_NAME" > "$SBATCHMAN_JOB_DIR/$BIN_NAME".asm'
        check: '[[ -f "../../bin/$BIN_NAME" ]]'

      # Atomic and CNAlock
      - tag: "compile_MergedCSR-BFS_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{implementation}_{chunksize}_{ncpus}"
        variables:
          implementation: ['atomic', 'cnalock']
        preprocess: |
          mkdir -p bin
          cd MergedCSR_{implementation}
          make clean
          BIN_NAME="bfs_{implementation}_chunksize{chunksize}_{ncpus}cpus_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}"
        command: "CHUNK_SIZE={chunksize} MAX_THREADS={ncpus} make bin/bfs"
        postprocess: 'mv bin/bfs "../bin/$BIN_NAME" && {compiler_disass[compiler]} "../bin/$BIN_NAME" > "$SBATCHMAN_JOB_DIR/$BIN_NAME".asm'
        check: '[[ -f "../bin/$BIN_NAME" ]]'

      # OpenMP target (single, built with CMake)
      - tag: "compile_MergedCSR-BFS_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{implementation}_{chunksize}"
        variables:
          implementation: ['openmp']
        preprocess: |
          mkdir -p bin
          cd MergedCSR_{implementation}
          rm -rf build
          cat > CMakeLists.txt<< EOF
          cmake_minimum_required(VERSION 3.20)
          project(BFS)
          set(CMAKE_CXX_STANDARD 20)
          set(CMAKE_CXX_STANDARD_REQUIRED True)
          set(CMAKE_CXX_FLAGS "{compiler_opt[compiler]} {compiler_common[compiler]} {compiler_march} {compiler_extra_flags[compiler_extra_flags_name]}")
          message("CMAKE_CXX_FLAGS --> \${CMAKE_CXX_FLAGS}")
          include_directories(include)
          file(GLOB_RECURSE SOURCES "src/*.cpp" "src/implementations/*.cpp")
          add_executable(BFS \${SOURCES})
          add_subdirectory(distributed_mmio)
          target_link_libraries(BFS PRIVATE distributed_mmio)
          EOF
          BIN_NAME="bfs_{implementation}_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}"
        command: 'cmake -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CXX_FLAGS="{compiler_opt[compiler]} {compiler_common[compiler]} {compiler_march} {compiler_extra_flags[compiler_extra_flags_name]}" -B build && make -C build BFS'
        postprocess: 'mv build/BFS "../bin/$BIN_NAME" && {compiler_disass[compiler]} "../bin/$BIN_NAME" > "$SBATCHMAN_JOB_DIR/$BIN_NAME".asm'
        check: '[[ -f "../bin/$BIN_NAME" ]]'

      # GAP
      - tag: "compile_MergedCSR-BFS_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{implementation}_{chunksize}"
        variables:
          implementation: ['gap']
        preprocess: |
          mkdir -p bin
          cd MergedCSR_mutex/gapbs
          cat > Makefile<< EOF
          CXX = {compiler_cxx[compiler]}
          CXX_FLAGS = {compiler_opt[compiler]} {compiler_common[compiler]} {compiler_march} {compiler_extra_flags[compiler_extra_flags_name]}

          KERNELS = bc bfs cc cc_sv pr pr_spmv sssp tc
          SUITE = \$(KERNELS) converter

          .PHONY: all
          all: \$(SUITE)

          % : src/%.cc src/*.h
          	\$(CXX) \$(CXX_FLAGS) $< -o \$@

          .PHONY: clean
          clean:
          	rm -f \$(SUITE) test/out/*
          EOF
          make clean
          BIN_NAME="bfs_{implementation}_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}"
        command: 'make bfs'
        postprocess: 'mv bfs "../../bin/$BIN_NAME" && {compiler_disass[compiler]} "../../bin/$BIN_NAME" > "$SBATCHMAN_JOB_DIR/$BIN_NAME".asm'
        check: '[[ -f "../../bin/$BIN_NAME" ]]'
