configs: "../common/sbm_configs/shared_memory.yaml"
include_variables:
  - "../common/sbm_configs/shared_memory_vars.yaml"
  - "vars.yaml"

variables:
  graph: "graphs/matrices_list_mtx.txt"
  nruns: [15]

  # TODO delete
  compiler_opt:
    map:
      default: ['-O3']
  compiler_extra_flags_name:
    map:
      default: ['autovec']

preprocess: "{energy_measure_start}"
postprocess: "{energy_measure_stop}"

jobs:
  - config: "{compiler}__{compiler_opt[compiler]}__{compiler_extra_flags_name[compiler]}____{ncpus}"
    config_jobs:
      - tag: "MergedCSR-BFS_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{implementation}_{chunksize}_{graph_filename}_{ncpus}"
        variables:
          implementation: ['mutex', 'atomic', 'cnalock']
        command: "bin/bfs_{implementation}_chunksize{chunksize}_{ncpus}cpus_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]} -f {graph} -n {nruns}"

      - tag: "MergedCSR-BFS_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{implementation}_{chunksize}_{graph_filename}_{ncpus}"
        variables:
          implementation: ['openmp']
        command: "bin/bfs_{implementation}_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}  -f {graph} -n {nruns}"
      
      - tag: "MergedCSR-BFS_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{implementation}_{chunksize}_{graph_filename}_{ncpus}"
        variables:
          implementation: ['gap']
        command: "bin/bfs_{implementation}_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]} -f {graph} -n {nruns}"
