variables:
  nodes: [2, 4, 6, 8, 10, 12, 14, 16, 18, 32, 64] # , 128, 256, 512, 1024]
  gpus: [2, 4]

isarco:
  scheduler: local

  default_conf:
    time: "00:03:00"
    modules: 
      - "nvhpc-hpcx-cuda13/26.1"

  configs:
    - name: "gpus_{gpus}"

nvl72:
  scheduler: slurm

  default_conf:
    # Change me as needed
    partition: "gamoraq"
    time: "00:03:00"
    # gpus: 4
    # qos: "?"
    exclusive: true
    custom_headers:
      - "#SBATCH --ntasks-per-node=4"

    # SPECIFY IF NEEDED
    # modules: 
    #   - ""

  configs:
    - name: "{nodes}_nodes"
      nodes: "{nodes}"

leonardo:
  scheduler: slurm

  default_conf:
    account: "IscrC_OMG-25"
    cpus_per_task: 8
    gpus: 4
    time: "00:03:00"
    partition: "boost_usr_prod"
    qos: "normal"
    exclusive: true
    custom_headers:
      - "#SBATCH --ntasks-per-node=4"
    modules: 
      - "gcc/12.2.0"
      - "openmpi/4.1.6--gcc--12.2.0-cuda-12.2"
      - "nvhpc/24.5"

  configs:
    - name: "{nodes}_nodes"
      nodes: "{nodes}"
      env:
        - "NCCL_IB_SL=1"
        - "UCX_IB_SL=1"
