variables:
  nodes: [2, 4, 6, 8, 10, 12, 14, 16, 32, 64, 128, 256]
  
  leonardo_service_level: [0, 1]

leonardo:
  scheduler: slurm

  default_conf:
    account: "IscrC_OMG-25"
    cpus_per_task: 1
    time: "00:10:00"
    partition: "boost_usr_prod"
    qos: "normal"
    gpus: 4
    modules: 
      - "gcc/12.2.0"
      - "openmpi/4.1.6--gcc--12.2.0-cuda-12.2"
      - "nvhpc/24.5"

  configs:
    - name: "leonardo__boost_usr_prod-{leonardo_service_level}__{nodes}_nodes"
      nodes: "{nodes}"
      custom_headers:
        - "#SBATCH --ntasks-per-node=4"
      env:
        - "NCCL_IB_SL={leonardo_service_level}"
        - "UCX_IB_SL={leonardo_service_level}"

alps:
  scheduler: slurm

  default_conf:
    account: "lp100"
    cpus_per_task: 1
    time: "00:05:00"
    partition: "normal"
    gpus: 4
    modules:
      - "gcc/13.2.0"
      - "cuda/12.4.0"
      - "nccl/2.20.3-1"
      - "cray-mpich/8.1.30"
    custom_headers:
      - "#SBATCH --uenv=prgenv-gnu/24.7:v3"
      - "#SBATCH --view=modules"
      - "#SBATCH --ntasks-per-node=4"

  configs:
    - name: "alps__normal__{nodes}_nodes"
      nodes: "{nodes}"

lumi:
  scheduler: slurm

  default_conf:
    account: "project_465002469"
    cpus_per_task: 1
    time: "00:05:00"
    partition: "standard-g"
    gpus: 8
    modules:
      - "LUMI/25.03 partition/G"
    custom_headers:
      - "#SBATCH --ntasks-per-node=8"
  configs:
    - name: "lumi__standard-g__{nodes}_nodes"
      nodes: "{nodes}"

baldo:
  scheduler: slurm

  default_conf:
    partition: "short"
    nodes: 1
    time: "00:00:40"
    modules:
      - "NVHPC/nvhpc/24.7"
  configs:
    - name: "baldo__short__2_nodes"
      gpus: 2
      cpus_per_task: 4
      custom_headers:
        - "#SBATCH --ntasks-per-node=2"
    - name: "baldo__short__4_nodes"
      gpus: 4
      cpus_per_task: 4
      custom_headers:
        - "#SBATCH --ntasks-per-node=4"
