sequential: true

variables:
  nodes: [10]             # Ensure these are enough for the experiments that will run
  system: ['leonardo']    # Does not matter if placement != runtime

  # -- Change as needed --
  experiment: "experiments_test/"
  # experiment: "experiments/"

  walltime: [40]

jobs:
  - config: "{nodes}_nodes"
    config_jobs:
      - tag: "{experiment_filename}"
        preprocess: "echo \"Allocated nodes: $SLURM_JOB_NODELIST\""
        command: "python workerpool_scheduler.py --walltime {walltime} --nodelist \"$SLURM_JOB_NODELIST\" --system {system} --debug -p {experiment}"
