sequential: true

variables:
  nodes: [8]
  # experiment: "experiments/"
  experiment: ["test_8_nodes.json"]

  walltime: [35]

jobs:
  - config: "{nodes}_nodes"
    config_jobs:
      - tag: "{experiment}"
        preprocess: "echo \"Allocated nodes: $SLURM_JOB_NODELIST\""
        command: "python workerpool_scheduler.py --walltime {walltime} --nodelist \"$SLURM_JOB_NODELIST\" --debug -p {experiment}"
