variables:
  pioneer_ncpus: [1, 2, 4, 8, 16, 32, 64]
  bananaf3_ncpus: [1, 2, 4, 8]
  arriesgado_ncpus: [1, 2, 4]

hca:
  scheduler: slurm

  default_conf:
    nodes: 1
    ntasks: 1
    exclusive: true
    time: "04:00:00"

  configs:
    - name: "pioneer_{pioneer_ncpus}cpus"
      partition: "pioneer"
      cpus_per_task: "{pioneer_ncpus}"
      env:
        - "OMP_NUM_THREADS={pioneer_ncpus}"

    # - name: "arriesgado_{arriesgado_ncpus}cpus"
    #   partition: "arriesgado-jammy"
    #   cpus_per_task: "{arriesgado_ncpus}"
    #   env:
    #     - "OMP_NUM_THREADS={arriesgado_ncpus}"

    # - name: "bananaf3_{bananaf3_ncpus}cpus"
    #   partition: "bananaf3"
    #   cpus_per_task: "{bananaf3_ncpus}"
    #   env:
    #     - "OMP_NUM_THREADS={bananaf3_ncpus}"

leonardo:
  scheduler: slurm

  default_conf:
    account: "IscrC_OMG-25_0"
    time: "01:00:00"
    partition: "dcgp_usr_prod"
    qos: "normal"
    exclusive: true
    nodes: 1
    ntasks: 1
    custom_headers:
      - "#SBATCH --gres=gres/tmpfs:10g"

  configs:
    - name: "leonardo-dcgp_{pioneer_ncpus}cpus"
      cpus_per_task: "{pioneer_ncpus}"
      modules: 
        - "gcc/12.2.0"
      env: 
        - "OMP_NUM_THREADS={pioneer_ncpus}"

    - name: "leonardo-dcgp-llvm_{pioneer_ncpus}cpus"
      cpus_per_task: "{pioneer_ncpus}"
      modules: 
        - "llvm/14.0.6--gcc--12.2.0-cuda-12.2"
      env: 
        - "OMP_NUM_THREADS={pioneer_ncpus}"
