variables:
  partition: ['dcgp']

  compiler: ["gcc", "clang", "icx"]
  libs: ['']
 
  ncpus: [1, 2, 4, 8, 16, 32, 56, 64, 112] # leonardo
  
  # ncpus: [1, 2, 4, 8, 16, 32, 64] # pioneer
  # bananaf3_ncpus: [1, 2, 4, 8]
  # arriesgado_ncpus: [1, 2, 4]

jobs:
  - config: "{partition}__{compiler}__{libs}__{ncpus}"
    command: >
      build_{compiler}_default/bin/raja-perf.exe
      -v Base_Seq Base_OpenMP RAJA_Seq RAJA_OpenMP
      --outdir ./results/{compiler}/{libs}/{ncpus}cpus
    config_jobs:
      - tag: "rajaperf__{compiler}__{libs}__{ncpus}"
