variables:
  # partition: ["dcgp"]
  # compiler: ["gcc", "clang", "icx"]
  # ncpus: [1, 2, 4, 8, 16, 32, 56, 64, 112]

  partition: ["rc01"]
  compiler: ["gcc", "clang"]
  ncpus: [1, 2, 4, 8, 16, 32, 56, 64, 96, 128]

  libs: ['']

  data_type:
    - "double"
    - "uint32"
    - "float"
    - "int32"

  # Footprint of a single array
  array_mem:
    - 512
    # - 8

command: "./bin/{compiler}/stream_{compiler}_{data_type}_M{array_mem}_R15_O0"

jobs:
  - config: "{partition}__{compiler}__{libs}__{ncpus}"
    config_jobs:
      - tag: "stream_{compiler}_{libs}_{data_type}_M{array_mem}_C{ncpus}"
      