sequential: true

configs: "../common/sbm_configs/shared_memory.yaml"
include_variables:
  - "../common/sbm_configs/shared_memory_vars.yaml"
  - "vars.yaml"


jobs:
  - config: "{compiler}__{compiler_opt}__{compiler_extra_flags_name}____{ncpus}"
    config_jobs:
      - tag:          "stream_{compiler}_{libs}_{data_type}_M{array_mem_mb}_C{ncpus}_R{runs}_O{offset}"
        preprocess:   "python3 ../common/energy/ncm.py start --core 0 --output /scratch/$(whoami)/energy_stream_{compiler}_{compiler_opt}_{compiler_extra_flags_name}_{libs}_{data_type}_M{array_mem_mb}_C{ncpus}_R{runs}_O{offset}.log"
        command:      "./bin/stream_{compiler}_{data_type}_M{array_mem_mb}_R{runs}_O{offset}"
        postprocess:  "python3 ../common/energy/ncm.py stop"
