sequential: true

configs: "../common/sbm_configs/shared_memory.yaml"
include_variables:
  - "../common/sbm_configs/shared_memory_vars.yaml"
  
command: './compile.sh'

jobs:
  - config: ""
    config_jobs:
      - tag: ""
