sequential: true

configs: "../common/sbm_configs/shared_memory.yaml"
include_variables:
  - "../common/sbm_configs/shared_memory_vars.yaml"
  - "../common/sbm_configs/shared_memory_only_one_compiler.yaml"
  - "vars.yaml"


check: '[[ -f "../bin/$BIN_NAME" ]]'

jobs:
  - config: "{compiler}__{compiler_opt[compiler]}__{compiler_extra_flags_name[compiler]}____1"
    config_jobs:

      # linear-chase
      - tag: "compile_linear-chase_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{linear_chase_max_stride}"
        category: "compile"
        preprocess: |
          mkdir -p bin
          cd pointer-chasing
          make clean
          BIN_NAME="linear-chase_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{linear_chase_max_stride}"
        command: 'make CFLAGS="$CFLAGS" CUSTOM_PREPROCESSOR_VARS="-DLINEAR_CHASE_MAX_STRIDE={linear_chase_max_stride}" bin/linear-chase'
        postprocess: 'mv bin/linear-chase "../bin/$BIN_NAME"'
        

      # fused-linear-chase
      - tag: "compile_fused-linear-chase_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{fused_linear_chase_max_stride}"
        category: "compile"
        preprocess: |
          mkdir -p bin
          cd pointer-chasing
          make clean
          BIN_NAME="fused-linear-chase_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{fused_linear_chase_max_stride}"
        command: 'make CFLAGS="$CFLAGS" CUSTOM_PREPROCESSOR_VARS="-DFUSED_LINEAR_CHASE_MAX_STRIDE={fused_linear_chase_max_stride}" bin/fused-linear-chase'
        postprocess: 'mv bin/fused-linear-chase "../bin/$BIN_NAME"'

      # random-chase
      - tag: "compile_random-chase_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{random_chase_max_size}"
        category: "compile"
        preprocess: |
          mkdir -p bin
          cd pointer-chasing
          make clean
          BIN_NAME="random-chase_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{random_chase_max_size}"
        command: 'make CFLAGS="$CFLAGS" CUSTOM_PREPROCESSOR_VARS="-DRANDOM_CHASE_MAX_SIZE={random_chase_max_size}" bin/random-chase'
        postprocess: 'mv bin/random-chase "../bin/$BIN_NAME"'

      # fused-random-chase
      - tag: "compile_fused-random-chase_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{fused_random_chase_max_size}"
        category: "compile"
        preprocess: |
          mkdir -p bin
          cd pointer-chasing
          make clean
          BIN_NAME="fused-random-chase_{compiler}_{compiler_opt[compiler]}_{compiler_extra_flags_name[compiler]}_{fused_random_chase_max_size}"
        command: 'make CFLAGS="$CFLAGS" CUSTOM_PREPROCESSOR_VARS="-DFUSED_RANDOM_CHASE_MAX_SIZE={fused_random_chase_max_size}" bin/fused-random-chase'
        postprocess: 'mv bin/fused-random-chase "../bin/$BIN_NAME"'
