variables:
  nodes: [1, 2, 4, 6, 8]
  gpus_per_node: [0, 4]
  gpus_per_node_isarco: [0, 1, 2, 3, 4]

  leonardo_service_level: [0, 1]


isarco:
  scheduler: local

  default_conf:
    modules: 
      - "nvhpc-hpcx-cuda13/26.1"

  configs:
    - name: "isarco__default__{gpus_per_node_isarco}_gpus__1_nodes"

leonardo:
  scheduler: slurm

  default_conf:
    account: "IscrC_OMG-25"
    cpus_per_task: 1
    time: "00:05:00"
    partition: "boost_usr_prod"
    qos: "normal"
    modules: # Make sure this is coherent with AXCCL config
      - "gcc/12.2.0"
      - "nvhpc/24.5"
      - "openmpi/4.1.6--gcc--12.2.0-cuda-12.2"
      # This saturates half the bandwidth - "hpcx-mpi/2.19"
    custom_headers:
      - "#SBATCH --ntasks-per-node=4"
    # env: FIXME, not working
    #   - "UCX_NET_DEVICES=mlx5$SLURM_LOCALID:1"

  configs:
    - name: "leonardo__boost_usr_prod-{leonardo_service_level}__{gpus_per_node}_gpus__{nodes}_nodes"
      nodes: "{nodes}"
      gpus: "{gpus_per_node}"
      env:
        - "NCCL_IB_SL={leonardo_service_level}"
        - "UCX_IB_SL={leonardo_service_level}"

alps-clariden:
  scheduler: slurm

  default_conf:
    account: "g220"
    exclusive: true
    cpus_per_task: 1
    time: "00:05:00"
    partition: "normal"
    custom_headers:
      - "#SBATCH --uenv=prgenv-gnu/26.3:v1"
      - "#SBATCH --view=default"
      - "#SBATCH --gpus-per-task=1"

  configs:
    - name: "{gpus_per_node}_gpus__{nodes}_nodes"
      nodes: "{nodes}"
      gpus: "{gpus_per_node}"
      custom_headers:
        - "#SBATCH --ntasks-per-node={gpus_per_node}"

jupiter:
  scheduler: slurm

  default_conf:
    account: "exalab"
    cpus_per_task: 72
    time: "00:02:00"
    partition: "booster"
    modules: # Make sure this is coherent with AXCCL config
      - "nvidia-compilers/25.9-CUDA-13"
      - "OpenMPI/5.0.8"
    custom_headers:
      - "#SBATCH --ntasks-per-node=4"

  configs:
    - name: "jupiter__booster__{gpus_per_node}_gpus__{nodes}_nodes"
      nodes: "{nodes}"
      gpus: "{gpus_per_node}"
