# Uncomment the following line if you want experiments to run one after the another
# sequential: true

variables:
  # System info
  system: ['leonardo']
  system_upper: ['LEONARDO']
  partition: ['boost_usr_prod']

  # The number of nodes can be incremented to have a better chance to satisfy the placement 
  nodes: [4]

  # This will increase buffer sizes up to 2^29 Bytes = 512 MiB
  buff_cycle: [29]

  # peering='process' means that only a pair of precesses communicate
  peering: ['process']

  # Peers distance: 2.0 = same L1, 4.0 = same group, different L1, 5.0 = different group
  peers_distance: [2.0, 4.0, 5.0]

# In case it is not possible to satisfy placements constraints, this will fail with return code 456
preprocess: |
  # Make sure you ran the `init.sh` script that generates this file
  source ./hicrest-axccl/configure/{system_upper}_DEFAULT.conf

  echo "--- Searching for desired topology within $SLURM_JOB_NUM_NODES nodes ---"
  echo "Allocated nodes: $SLURM_JOB_NODELIST"

  # Run the tool and capture output
  TOPO_OUTPUT=$(../common/JobPlacer/target/release/job_placer -s {system} --topology-scontrol <(cat <<EOF
  {
      "constraints": [
          {
              "type": "NodesAtDistance",
              "count": 1,
              "distance": {peers_distance},
              "reference": "First"
          }
      ]
  }
  EOF
  ))
  TOPO_EXIT_CODE=$?

  echo "Tool exit code: $TOPO_EXIT_CODE"
  echo "Tool output: $TOPO_OUTPUT"

  # Check if the command failed
  if [ $TOPO_EXIT_CODE -ne 0 ]; then
      echo "❌ ERROR: Topology search failed with exit code $TOPO_EXIT_CODE."
      exit 1
  fi

  SELECTED_NODES="$TOPO_OUTPUT"
  echo "✅ SUCCESS! Selected Nodes: $SELECTED_NODES"


jobs:
  # The number of nodes can be incremented to have a better chance to satisfy the placement 
  - config: "{system}__{partition}__1_tasks_per_node__1_gpus__{nodes}_nodes"
    config_jobs:

      # Peer-to-Peer
      - tag: "p2p__gpu_buff__{implementation}__distance_{peers_distance}"
        variables:
          implementation:
            - 'CudaAware'
            - 'Baseline'
            # - 'Nccl'
        command: "srun -N 2 -w \"$SELECTED_NODES\" ./hicrest-axccl/bin/std/p2p_{implementation} --buff-cycle {buff_cycle} --peering {peering}"

      # Ping-Pong
      - tag: "pingpong__gpu_buff__{implementation}__distance_{peers_distance}"
        variables:
          implementation:
            - 'CudaAware'
            - 'Baseline'
            # - 'Nccl'
        command: "srun -N 2 -w \"$SELECTED_NODES\" ./hicrest-axccl/bin/std/pingpong_{implementation} --buff-cycle {buff_cycle} --peering {peering}"


      # - tag: "pp__cpu_buff__{implementation}"
      #   variables:
      #     implementation:
      #       - 'host2host_Host'
      #   command: "mpirun -np 8 ./bin/hostmem/pp_{implementation} --buff-cycle {buff_cycle} --peering {peering}"