# Uncomment the following line if you want experiments to run one after the another
# sequential: true

variables:
  # System info (comment as needed)
  # system: ['alps']
  # system_upper: ['ALPS']
  # partition: ['normal'] 

  system: ['leonardo']
  system_upper: ['LEONARDO']
  partition: ['boost_usr_prod-1'] # format: partition-serviceLevel

  #------------------------------------------

  # The number of nodes can be incremented to have a better chance to satisfy the placement 
  nodes: [2]
  gpus_per_node: [4]

  # This will increase buffer sizes up to 2^30 Bytes = 1 GiB
  buff_cycle: [30]

  # peering='process' means that only a pair of precesses communicate
  # peering='node' means that all processes form one node communicate with the same-rank process on the other (i.e., in pairs)
  peering: ['node']

  implementation:
    - 'CudaAware'
    - 'Baseline'
    # - 'Nccl'

  primitive:
    - 'p2p'       # Peer-to-Peer
    - 'pingpong'  # Ping-Pong

  collective:
    - 'a2a'     # All-to-All
    - 'ar'      # All-Reduce

  buffer_type:
    - 'devicebuff' # GPU to GPU communication

  # Peers distance: 2.0 = same L1, 4.0 = same group, different L1, 5.0 = different group
  peers_distance: [2.0, 4.0, 5.0]

# In case it is not possible to satisfy placements constraints, this will fail
preprocess: |
  # Make sure you ran the `init.sh` script that generates this file
  source ./hicrest-axccl/configure/{system_upper}_DEFAULT.conf

  echo "--- Searching for desired topology within $SLURM_JOB_NUM_NODES nodes ---"
  echo "Allocated nodes: $SLURM_JOB_NODELIST"

  # Run the tool and capture output
  TOPO_OUTPUT=$(../common/JobPlacer/target/release/job_placer -s {system} --topology-scontrol <(cat <<EOF
  {
      "constraints": [
          {
              "type": "NodesAtDistance",
              "count": 1,
              "distance": {peers_distance},
              "reference": "First"
          }
      ]
  }
  EOF
  ))
  TOPO_EXIT_CODE=$?

  echo "Tool exit code: $TOPO_EXIT_CODE"
  echo "Tool output: $TOPO_OUTPUT"

  # Check if the command failed
  if [ $TOPO_EXIT_CODE -ne 0 ]; then
      echo "❌ ERROR: Topology search failed with exit code $TOPO_EXIT_CODE."
      exit 1
  fi

  SELECTED_NODES="$TOPO_OUTPUT"
  echo "✅ SUCCESS! Selected Nodes: $SELECTED_NODES"


jobs:
  # The number of nodes can be incremented to have a better chance to satisfy the placement 
  - config: "{system}__{partition}__{gpus_per_node}_gpus__{nodes}_nodes"
    config_jobs:

      - tag: "{primitive}__{buffer_type}__{implementation}__{peering}__{buff_cycle}__{peers_distance}"
        command: "srun -N 2 -w \"$SELECTED_NODES\" ./hicrest-axccl/bin/std/{buffer_type}/{primitive}_{implementation} --buff-cycle {buff_cycle} --peering {peering}"

      - tag: "{collective}__{buffer_type}__{implementation}__na__{buff_cycle}__{peers_distance}"
        command: "srun -N 2 -w \"$SELECTED_NODES\" ./hicrest-axccl/bin/std/{buffer_type}/{collective}_{implementation} --buff-cycle {buff_cycle}"