# Uncomment the following line if you want experiments to run one after the another
# sequential: true

variables:

  nodes: [2]
  gpus_per_node: [4]

  # This will increase buffer sizes up to 2^30 Bytes = 1 GiB
  buff_cycle: [30]

  implementation:
    - 'CudaAware'
    # - 'Baseline'
    # - 'Nccl'

  collective:
    - 'a2a'     # All-to-All
    - 'ar'      # All-Reduce
    # - 'agth'    # All-Gather
    # - 'rs'      # Reduce-Scatter

  buffer_type:
    - 'devicebuff' # GPU to GPU communication

preprocess: |
  echo "Allocated nodes: $SLURM_JOB_NODELIST"
  echo "CUDA devides: $CUDA_VISIBLE_DEVICES"


jobs:
  # The number of nodes can be incremented to have a better chance to satisfy the placement 
  - config: "{gpus_per_node}_gpus__{nodes}_nodes"
    config_jobs:
      - tag: "axccl_{collective}_{implementation}_{buffer_type}_{buff_cycle}_na_unknown"
        command: "srun -N {nodes} ./hicrest-axccl/build/bin/std/{buffer_type}/{collective}_{implementation} --buff-cycle {buff_cycle}"